#!/bin/bash
# v1.4 File Reorganization Script
# Generated by ∞ 2026-03-20

set -e

echo "Starting v1.4 file cleanup..."

# 1. Create directory structure
mkdir -p docs/v1.4/phase-reports
mkdir -p docs/v1.4/theory
mkdir -p scripts/debug
mkdir -p archive/v1.4-temp

# 2. Move Phase reports to docs/v1.4/phase-reports/
echo "Moving Phase reports..."
mv PHASE*.md docs/v1.4/phase-reports/ 2>/dev/null || true
mv FILE_MANIFEST*.txt docs/v1.4/phase-reports/ 2>/dev/null || true
mv PHASE*.txt docs/v1.4/phase-reports/ 2>/dev/null || true

# 3. Move v1.4 README to docs/v1.4/
echo "Moving v1.4 README..."
mv README_v1_4.md docs/v1.4/ 2>/dev/null || true

# 4. Move debug scripts to scripts/debug/
echo "Moving debug scripts..."
mv diagnose_*.py scripts/debug/ 2>/dev/null || true
mv debug_*.py scripts/debug/ 2>/dev/null || true
mv test_fix_*.py scripts/debug/ 2>/dev/null || true
mv test_manufactured_*.py scripts/debug/ 2>/dev/null || true
mv derive_*.py scripts/debug/ 2>/dev/null || true
mv run_diagnostics_tests.py scripts/debug/ 2>/dev/null || true

# 5. Move theory docs
echo "Moving theory docs..."
mv energy_theorem_toroidal.md docs/v1.4/theory/ 2>/dev/null || true

# 6. Archive temporary files (don't delete, in case needed)
echo "Archiving temporary files..."
mv *.log archive/v1.4-temp/ 2>/dev/null || true
mv *.pid archive/v1.4-temp/ 2>/dev/null || true
mv *.png archive/v1.4-temp/ 2>/dev/null || true
mv *.zip archive/v1.4-temp/ 2>/dev/null || true
mv *.txt archive/v1.4-temp/ 2>/dev/null || true
mv trace_*.py archive/v1.4-temp/ 2>/dev/null || true
mv verify_phase3.sh archive/v1.4-temp/ 2>/dev/null || true

# 7. Summary
echo ""
echo "Cleanup complete!"
echo ""
echo "New structure:"
echo "  docs/v1.4/phase-reports/ - Phase completion reports"
echo "  docs/v1.4/theory/ - Theory documentation"
echo "  scripts/debug/ - Debug and diagnostic scripts"
echo "  archive/v1.4-temp/ - Temporary files (logs, pids, plots)"
echo ""
echo "Root directory now clean. Ready for git add."
